spring:
  application:
    name: kpi-dashboard-api
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

graphql:
  packages:
    - "com.example.life"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
