spring:
  application:
    name: life-api
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  data:
    redis:
      host: localhost
      port: 6379

graphql:
  packages:
    - "com.example.life"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
