spring:
  application:
    name: life-api
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  data:
    redis:
      host: localhost
      port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
  flyway:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/your_database
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

graphql:
  packages:
    - "com.example.life"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.r2dbc.postgresql: DEBUG
